---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.github.com
  resources:
  - podgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.github.com
  resources:
  - podgroups/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.github.com
  resources:
  - podgroups/status
  verbs:
  - get
  - patch
  - update
