apiVersion: scheduling.github.com/v1
kind: PodGroup
metadata:
  labels:
    app.kubernetes.io/name: gang-scheduler-api
    app.kubernetes.io/managed-by: kustomize
  name: podgroup-sample
spec:
  group_name: podgroup-sample
  min_num: 3